[package]
name = "chat_sse_demo"
version = "0.1.0"
authors = ["aedius filmania <aedius.filmania@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"